# Generated by Django 5.0.7 on 2024-08-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_applicationuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
